### ISSUE TITLE
Add empty option in SelectField

### ISSUE THREAD

**Issue by anselal** [wtforms/flask-wtf#348]
Hi there,

is there a way to add an empty option to a Selectfield ?
The only way I found is to add this to the choices before your actual choices:

```sh
[("", "-- select an option --")]
```

But this requires validation on the backend since this option should be disabled by default.

How can I disable this option so that the rendered tag would be like:

```sh
<option disabled="" selected="" value=""> -- select an option --</option>
```

**Comment by shaoeChen** [comment]
my way is:
first: set default on form filed
second: use '+' to add other option.
```python
# form.py
class TestForm(FlaskForm):
    dropdownlist = SelectField('dropdownlist')

# view.py
@app.route('/your_route')    
def your_function():
    form = TestForm()
    select_option = Model.query.with_entities('key', 'value').all()

    form.dropdownlist.default = [('0', '-- select an option --')] + select_option
    return ...
```
of course you can add SelectField's option in Form init.
Then while i insert into database, i will change 0 to None, if you set column null=True.

**Comment by anselal** [comment]
Not exactly what I was hoping to...

**Comment by 5uper5hoot** [comment]
If you are using an ORM (sqlalchemy/django) then the wtforms `QuerySelectField` from the relevant wtforms extension have an `allow_blank` argument, where if `True` adds a blank field automatically.

E.g.:
```
from wtforms.ext.sqlalchemy.fields import QuerySelectField
class AForm(Form):
    category = QuerySelectField(
        query_factory=lambda: Category.query, 
        allow_blank=True
    )
```
It hard to look past if you are already querying through ORM to get select options. 

Although the sqlalchemy extension is on the way out, to be replaced by  [WTForms-Alchemy](https://wtforms-alchemy.readthedocs.io/en/latest/) in 3.0.

**Comment by andy-takker** [comment]
Thank you very much for QuerySelectField!!!

**Comment by marrocelli** [comment]
My workaround for this was to include a custom validation function to not allow the first option, which might be something like "-- select an option --". I know this is not exactly what you were looking for and also 4 years late, but I hope this helps somebody haha

` 
# forms.py

class MyForm(FlaskForm):

    def validate_option(self, option_to_check):
        if option_to_check == "-- select an option --":
            raise ValidationError("Please select a role.")

option = SelectField(label="Choose an option", choices=[('-- select an option --'), ('Option 1'), ('Option 2'), ('Option 3'), ('Other')])

`

**Comment by ofurkusi** [comment]
Another option would be to make a custom `SelectField`, adjusting the original `pre_validate` function like so, that raises an error if the value of the option is an empty string (`""`):

```python
from wtforms.validators import ValidationError
from wtforms.fields import SelectField

class CustomSelectField(SelectField):
    """A custom Select field that does not allow empty fields."""

    def pre_validate(self, form):
        if self.choices is None:
            raise TypeError(self.gettext("Choices cannot be None."))

        if not self.validate_choice:
            return

        ## begin added code
        if self.data == "":
            raise ValidationError(self.gettext("You must select an option from the list."))
        ## stop added code

        for _, _, match in self.iter_choices():
            if match:
                break

        else:
            raise ValidationError(self.gettext("Not a valid choice."))
```

The "invalid" option should be defined e.g. like this:
```python
[("", "-- select an option --"), ("1", "A valid option"), ...]
```

**Comment by PanderMusubi** [comment]
Note that the text shown should also be supported by translation to other languages.

**Comment by vvalenzuela96** [comment]
The best way for disable an option or 'validate' a select field its the following:
``` python
the_field = SelectField(
    'The Field',
    choices=[('', 'Select any'), ('more_options', 'More Options')],
    validators=[InputRequired()],
    default=''
    )
```
Note:
Add these imports
``` python
from wtforms import SelectField
from wtforms.validators import InputRequired
```

**Comment by azmeuk** [comment]
Disabling the option with a HTML `disabled` attribute will come with https://github.com/wtforms/wtforms/pull/739
