### ISSUE TITLE
Why use referrer header for CSRF protection when you have sychronizer tokens?

### ISSUE THREAD

**Issue by knod** [wtforms/flask-wtf#364]
I'm new to the security game. I'd understood that a sychronizer token and a referrer header were doing basically the same thing, and that a sychronizer token is more robust. What does a referrer header add that a sychronizer token doesn't address?

**Comment by gsmethells** [comment]
I'll add a [reference to CSRF and sychronizer token from OWASP](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#synchronizer-token-pattern) and second the question.

**Comment by davidism** [comment]
Because that's how it was designed. Given that I don't have time to research an entirely new CSRF method, I don't really know what action you want on this issue.

**Comment by gsmethells** [comment]
`        if request.is_secure and current_app.config['WTF_CSRF_SSL_STRICT']:
            if not request.referrer:
                self._error_response('The referrer header is missing.')

            good_referrer = f'https://{request.host}/'

            if not same_origin(request.referrer, good_referrer):
                self._error_response('The referrer does not match the host.')`

**Comment by gsmethells** [comment]
Doing some research on OWASP, further down the same page linked earlier, [OWASP does recommend checking the Referer header but only if the Origin header is not present](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#checking-the-origin-header).

**Comment by gsmethells** [comment]
Mozilla links to the above HTTP header values:

- [Origin Header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin)
- [Referer Header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer)
- [X-Forwarded-Host (XFH) header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host)

**Comment by davidism** [comment]
> If request.is_secure is False (due to being behind nginx or a load-balancer that does SSL termination)

You need to configure your app with ProxyFix then. The app should know how it's proxied.

**Comment by gsmethells** [comment]
```
    # Proxy a Flask app nicely:  https://web.archive.org/web/20190128010140/http://flask.pocoo.org/snippets/35/
    proxy_set_header          Host  $http_host;
    proxy_set_header          X-Forwarded-Proto  https;
    proxy_set_header          X-Forwarded-For  $proxy_add_x_forwarded_for;
    proxy_set_header          X-Real-IP  $remote_addr;
    proxy_set_header          X-Scheme  $scheme;
    proxy_set_header          REMOTE_ADDR  $remote_addr;
```

For now we run nginx with this but will be moving to GCP and not reverse proxying with nginx any longer. We'll see, but that still does not touch on the Origin header vs Referer header topic.

**Comment by gsmethells** [comment]
As far as the original question is concerned, [OWASP suggests](https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html#introduction) to:

1. Check if your framework has built-in CSRF protection and use it
2. For stateful software use the synchronizer token pattern
3. For stateless software use double submit cookies
4. Implement at least one mitigation from Defense in Depth Mitigations section

where (4) includes:

1. Consider SameSite Cookie Attribute for session cookies
2. Consider implementing user interaction based protection for highly sensitive operations
3. Consider the use of custom request headers
4. Consider verifying the origin with standard headers

hence, the answer to this ticket is that **both** "synchronizer token pattern" and "verifying the origin" are necessary to meet OWASP security standards. 

So, if there are no other topics other than Origin header vs Referer header which I am still curious about, then this ticket should be closed based upon that research.

**Comment by gsmethells** [comment]
Here is [a link to proxy setups and ProxyFix](https://flask.palletsprojects.com/en/2.0.x/deploying/wsgi-standalone/#deploying-proxy-setups) for the curious reader who trundles here at a later date.
