### ISSUE TITLE
reCaptcha blocked in some countries - need configurable URL

### ISSUE THREAD

**Issue by mdsteveb** [wtforms/flask-wtf#384]
As per this reCaptcha FAQ:

https://developers.google.com/recaptcha/docs/faq#can-i-use-recaptcha-globally

Currently it appears to be hard-coded. Making this configurable would be a big help.

**Comment by patterson163** [comment]
> As per this reCaptcha FAQ:
> 
> https://developers.google.com/recaptcha/docs/faq#can-i-use-recaptcha-globally
> 
> Currently it appears to be hard-coded. Making this configurable would be a big help.

As mvolfik said,you can change your flask_wtf/recaptcha/widgets.py file.In it, change RECAPTCHA_SCRIPT = u'https://www.recaptcha.net/recaptcha/api.js'.Then,it works.

**Comment by tresni** [comment]
#342 and #387 both look to address this.

**Comment by azmeuk** [comment]
Fixed by #425
