### ISSUE TITLE
FlaskForm object returns wrong data after dynamically changed with JavaScript

### ISSUE THREAD

**Issue by NimaBavari** [wtforms/flask-wtf#459]
My environment: Python 3.9.2, Flask==2.0.1, Flask-WTF==0.15.1

I have a simple form:

```python
class RunReportForm(FlaskForm):
    report_name_1 = BooleanField('First report')
    report_name_2 = BooleanField('Second report')
    additional = StringField('Additional reports')
    run = SubmitField('Run')
```

and in my views, I import it and use it:

```python
@app.route('/', methods=['GET', 'POST'])
def index():
    form = RunReportForm(request.form)
    if form.validate_on_submit():
        print([itm for itm in form])
    return render_template('index.html', form=form)
```

and I have a JS script that when you input anything into the StringField, when it reaches a comma, it adds a new BooleanField to the form with the label text up to that comma (and clears that StringField). So, when you submit the form, instead of giving me the latest state of the form, it gives me its initial state (i.e., the one defined in the RunReportForm).

**Comment by davidism** [comment]
What you're describing isn't particularly supported by WTForms. You can look at `FieldList` and `FormField` to process a dynamic list of fields, assuming your JS names them as expected. Or you might be able to override form creation to create fields based on some incomming data.
