### ISSUE TITLE
BooleanField does not honor default value with GET requests

### ISSUE THREAD

**Issue by Ghost99** [wtforms/flask-wtf#464]
Form initialization with `form = Form(formdata=request.args)` handles default value of BooleanField incorrectly. When being initialized from empty GET request it set BooleanField value to False even it have default=True.

Tested with:
Flask-2.0.1
Flask-WTF-0.15.1
WTForms-2.3.3
python-3.9.6

Here is complete sample:
`sample.py`:
```
from flask import Flask, request, render_template
from flask_wtf import FlaskForm
from wtforms import BooleanField, StringField

app = Flask(__name__)
app.config.update({
    'SECRET_KEY': 'qwertyofcourse',
})


class TestForm(FlaskForm):
    field1 = StringField(default='Pain peko')
    field2 = BooleanField(default=True)


@app.route('/')
def index():
    form = TestForm(formdata=request.args)
    return render_template('index.html', form=form)


if __name__ == '__main__':
    app.run(debug=True, port=12345)

```

`templates/index.html`:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Buggy form</title>
</head>
<body>
<form method="get">
    This field default value is ok<br>
    {{ form.field1.label }} - {{ form.field1 }}<br>
    <br>
    But this field should be set to True by default, but it is not.<br>
    {{ form.field2.label }} - {{ form.field2 }}<br>
    <input type="submit">
</form>
</body>
</html>
```

As you can see, when you run `sample.py` and open localhost:12345 you will see field2 value is False with empty GET request data. But it should be True by default. Field1 handling work as expected.

**Comment by davidism** [comment]
Boolean values are weird in HTML forms. You cannot reliably have defaults or detect unset boolean values.
