### ISSUE TITLE
csrf.exempt  CSRF fails under nested blueprints

### ISSUE THREAD

**Issue by kanhebei** [wtforms/flask-wtf#486]
When adding `csrf.exempt` on a blueprint that has a child blueprint, it only works on the parent blueprint.

```python
bp_main = Blueprint('main', __name__)
csrf.exempt(bp_main)

bp_child = Blueprint('child', __name__)

bp_main.register_blueprint(bp_child)
```

**Comment by Zianor** [comment]
I'd really like to fix it, but I wonder if it's better to check all blueprints in the before_request section with `if any([blueprint in self._exempt_blueprints for blueprint in request.blueprints]):` (csrf.py, line 220) or to add child blueprints recursively when adding a blueprint to `self._exempt_blueprints` (csrf.py, line 295). The first one would be much more readable but less performant, the second one would bug, if new blueprints are registered on the blueprint after adding it to the excemts.

Any opinions on this?

**Comment by jeremywilkinson** [comment]
Unfortunately I'm not qualified to give an opinion on this, but having just run into this issue myself, I thought I'd comment to re-raise the issue.

Especially since explicitly marking sub-blueprints as csrf exempt also seems not to work:

```
from flask import Flask, Blueprint
from flask_wtf import CSRFProtect

app = Flask(__name__)
app.config.from_mapping({
    'API_TITLE': 'TEST API',
    'API_VERSION': 0.1,
})
app.secret_key = 'SOME_SECRET'
csrf = CSRFProtect(app)

blp1 = Blueprint('blp-one', __name__, url_prefix='/blp-one')
blp2 = Blueprint('blp-two', __name__, url_prefix='/blp-two')

@blp1.route('/test', methods=('POST',))
def post_test():
    return 'OK'

@blp2.route('/test', methods=('POST',))
def post_test():
    return 'OK'

blp1.register_blueprint(blp2)
app.register_blueprint(blp1)

csrf.exempt(blp1)
csrf.exempt(blp2)

app.run(port=12345)
```

As this demonstrates

```
import requests

ret = requests.post('http://localhost:12345/blp-one/test')
assert ret.status_code == 200
ret = requests.post('http://localhost:12345/blp-one/blp-two/test')
assert ret.status_code == 400

print(ret.text)
"""
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>The CSRF token is missing.</p>
"""
```

**Comment by azmeuk** [comment]
Fix released in 1.1.2

**Comment by Zianor** [comment]
I don't know whether it is intended, but an exempt on the parent blueprint still leads to the views of the nested blueprint to be protected.
From what you did in the tests, i would have expected that exempting the parent would lead to the children being exempted as well.

**Comment by Zianor** [comment]
In some of my projects we splitted a bigger exempted blueprint into multiple smaller nested blueprints, that should all share the exempt of the parent. Exempting them individually is possible but was not intuitive to me, since conceptually they are part of the parent blueprint

**Comment by azmeuk** [comment]
One thing I am not sure how to deal with is a situation like this:

bp1 is exempted
bp2 is not exempted
bp3 is nested in bp1 and also in bp2

In that situation bp3 could be exempted or not exempted depending on the urls. I am wondering if that could cause difficulties in some ways :thinking:

**Comment by Zianor** [comment]
To be honest, I did not think of such a construct. Maybe one could use a config variable deciding if the the .blueprint is checked or if it is enough when any of the blueprints is exempted
