### ISSUE TITLE
csrf.exempt works only top blueprint

### ISSUE THREAD

**Issue by hynever** [wtforms/flask-wtf#487]
Environment:
- Python version: Python 3.10
- Flask-WTF version: 1.00
- Flask version: 2.0.2

```python
app = Flask(__name__)
csrf = CSRFProtect(app)

parent_bp = Blueprint("parent", __name__)
child_bp = Blueprint("child", __name__)

app.register_blueprint(parent_bp)
parent_bp.register_blueprint(child_bp)

# it works
csrf.exempt(parent_bp)

# it not works
csrf.exempt(child_bp)
```
after debug flask-wtf source code, i found the next code issue:
```python
# flask_wtf -> csrf.py line 220
if request.blueprint in self._exempt_blueprints:
    return
```
the `self._exempt_blueprints` only keep the blueprint name, without parent blueprint name.

of course, the primary issue is not here, but exempt method:
```python
# flask_wtf -> csrf.py line 295
if isinstance(view, Blueprint):
    self._exempt_blueprints.add(view.name)
        return view
```
the `view.name` should be replace other code that has full blueprint path

**Comment by davidism** [comment]
Duplicate of #486
