### ISSUE TITLE
BooleanField does not honor default value

### ISSUE THREAD

**Issue by ademaro** [wtforms/flask-wtf#489]
I'm having issues with rendering a BooleanField correctly

```python
from flask_wtf import FlaskForm
from wtforms import BooleanField

class TestForm(FlaskForm):
    check = BooleanField("mycheckbox", default="checked")
```
But it renders unchecked...

Works correctly if written like this:
```python
class TestForm(FlaskForm):
    check = BooleanField("mycheckbox", render_kw={"checked": True})
```

Environment: MacOS 12.0.1

- Python version: 3.9.8
- Flask-WTF version: 0.15.1
- Flask version: 2.0.2

**Comment by davidism** [comment]
Presumably it should be `default=True`.

**Comment by ademaro** [comment]
@davidism In general, it does not matter, but I tried with your version, the effect is the same...

**Comment by jnnkB** [comment]
I just tested it using the same environment and this code and it worked fine.

```python
from flask import Flask
from flask_wtf import FlaskForm
from wtforms import BooleanField


app = Flask(__name__)
app.secret_key = "VERY SECURE"

class TestForm(FlaskForm):
    check = BooleanField("mycheckbox", default="checked")
    check2 = BooleanField("mycheckbox", default=True)


@app.route("/")
def index():
    form = TestForm()
    return form.check() + form.check2()
```
This is the result:

<img width="55" alt="image" src="https://user-images.githubusercontent.com/29376715/142914797-0c495d28-7dfa-4cfa-b16f-f722492215e8.png">

```html
<input checked id="check" name="check" type="checkbox" value="y"><input checked id="check2" name="check2" type="checkbox" value="y">⏎
```

**Comment by ademaro** [comment]
My variant not worked about this line: `form = TestForm(request.form)`
```python
from flask import Flask, request
from flask_wtf import FlaskForm
from wtforms import BooleanField


app = Flask(__name__)
app.secret_key = "VERY SECURE"


class TestForm(FlaskForm):
    check = BooleanField("mycheckbox", default="checked")
    check2 = BooleanField("mycheckbox", default=True)


@app.route("/")
def index():
    form = TestForm(request.form)
    return form.check() + form.check2()
```

Now all good, thanks)
```python
# ...
if request.method == 'POST':
    form = TestForm(request.form)
else:
    form = TestForm()
```

**Comment by jnnkB** [comment]
Just a short note: flask-wtf provides validate_on_submit which checks the request method and validates the data. So if you do not intend to skip validation its probably good yo use this method. Here is a small code example:

```python
@app.route('/submit', methods=['GET', 'POST'])
def submit():
    form = MyForm()
    if form.validate_on_submit():
        return redirect('/success')
    return render_template('submit.html', form=form)
```

**Comment by ademaro** [comment]
@jnnkB Thanks, but in your example, saving the filled form fields after submitting the form, if errors occur in any of the fields, will not work in your example. Previously, I always passed the `request.form` to the constructor of the form class:
```python
form = MyForm(request.form)
```
But this stopped working with checkboxes, so I had to make an additional check:
```python
if request.method == 'POST':
    form = MyForm(request.form)
else:
    form = MyForm()
```
After these checks, of course, the real code contains `if form.validate_on_submit ():`.

I don't know how much better it can be done, but for now, like this...
