### ISSUE TITLE
Support forms with GET method

### ISSUE THREAD

**Issue by Miksus** [wtforms/flask-wtf#505]
It seems there has been [very brief discussion](https://github.com/wtforms/flask-wtf/issues/291) about this previously but to me it seems flask-wtf does not support forms with GET method as much as it could be. Current state causes issues with validation, keeping the form values when response is returned and causes extra confusion as the form fields cannot be used.

I have an idea to fix it.

## Current state: One could do this
In forms:
```python
class MyForm(FlaskForm):
    myfield = StringField("My label")
    submit = SubmitField("Search")
```

In tmpl.html
```html
<form method="GET">
   {{ form.myfield.label() }}
   {{ form.myfield() }}
   {{ form.submit.label() }}
   {{ form.submit() }}
</form>
```

In app.py
```python
@app.route("/my-url")
def my_route():
    form = MyForm()

    # Use the form args (if exists) for querying etc.
    qry_args = request.args
    ...

    return render_template("tmpl.html", form=form)
```

---
However, the issue is that:
1. The form does not maintain the field values. When the server returns the response, it does not have the form values anymore unless they are forced to the form which increases complexity.
2. The form cannot be used to manipulate the data.
3. Validation cannot be effectively used.

And why this is relevant:

- I found that using GET forms to make a query panel is pretty handy. Using flask-wtf could avoid some extra boilerplate but then I encountered this issue.

## Solution: Make it support forms with GET method

In FlaskForm's Meta:
```python
        def wrap_formdata(self, form, formdata):
            if formdata is _Auto:
                if _is_submitted():
                    if request.files:
                        return CombinedMultiDict((request.files, request.form))
                    elif request.form:
                        return request.form
                    elif request.get_json():
                        return ImmutableMultiDict(request.get_json())
                    elif request.args: 
                        # Make the form use URL parameters if nothing else
                        return request.args

                return None

            return formdata
```
Then the ``_is_submitted`` should be changed to support "GET". However, it seems some tests will fail if that is done thus I think either:
1. We need an attribute to identify whether the form is meant to be used as GET method 
2. or then we had another class (``FlaskGetForm``) for the job. However, because the Meta is embedded in the ``FlaskForm``, it is non-trivial (to me) how to subclass ``FlaskForm`` in user code.

Is this sensible? If so, I would be happy to work on the PR related to this.

**Comment by davidism** [comment]
Your "current state" code isn't correct, it should be `MyForm(request.args)`, then the listed issues are resolved.
