### ISSUE TITLE
Bug: Update to Request.get_json() in Werkzeug 2.1.0 breaks reCAPTCHA validation   

### ISSUE THREAD

**Issue by tonydangblog** [wtforms/flask-wtf#510]
## Bug: Update to Request.get_json() in Werkzeug 2.1.0 breaks reCAPTCHA validation  

# Bug Description
[pallets/werkzeug#2339](https://github.com/pallets/werkzeug/issues/2339) updated `Request.get_json()` to raise a 400 `BadRequest` error if the `Content-Type` header is not `application/json`.

In [flask-wtf/src/flask_wtf/recaptcha/validators.py](https://github.com/wtforms/flask-wtf/blob/main/src/flask_wtf/recaptcha/validators.py), `request.json` will raise a 400 `BadRequest` error if the `Content-Type` header is not `application/json` (i.e. when a form is submitted via POST request):
```py
class Recaptcha:
    """Validates a ReCaptcha."""

    ...

    def __call__(self, form, field):
        if current_app.testing:
            return True

        if request.json:
            response = request.json.get("g-recaptcha-response", "")
        else:
            response = request.form.get("g-recaptcha-response", "")
        ...
```

Possible solution is to replace `request.json` with `request.is_json`:
```diff
class Recaptcha:
    """Validates a ReCaptcha."""

    ...

    def __call__(self, form, field):
        if current_app.testing:
            return True

-       if request.json:
+       if request.is_json:
            response = request.json.get("g-recaptcha-response", "")
        else:
            response = request.form.get("g-recaptcha-response", "")
        ...
```

## Replication
Submit an html form via POST request that requires validation by `flask_wtf.RecaptchaField()`.

## Expected Behavior
Form validates.

## Actual Behavior
A 400 `BadRequest` error is raised.

## Environment

- Python version: 3.9.1
- Flask-WTF version: 1.0.0
- Flask version: 2.1.0

**Comment by davidism** [comment]
Sure, happy to review a PR.

**Comment by davidism** [comment]
Flask-WTF 1.0.1 is available: https://pypi.org/project/Flask-WTF/1.0.1/

**Comment by tonydangblog** [comment]
Ah darn, looks like I was too slow with my PR. Thanks for fixing this!
