### ISSUE TITLE
Update to Request.get_json() in Werkzeug 2.1.0 breaks empty forms

### ISSUE THREAD

**Issue by jwag956** [wtforms/flask-wtf#511]
Similar to #510 - the get_json() change in Werkzeug 2.1.0 https://github.com/pallets/werkzeug/issues/2339 breaks any empty submitted form (not json).
From form.py:
   
```
 def wrap_formdata(self, form, formdata):
            if formdata is _Auto:
                if _is_submitted():
                    if request.files:
                        return CombinedMultiDict((request.files, request.form))
                    elif request.form:
                        return request.form
                    elif request.get_json():
                        return ImmutableMultiDict(request.get_json())
```

If the form is an empty ImmutableMultiDict - it falls into the get_json() code which is then checking that the content-type header has been set to application/json.

Possible solution would be to change elif request.get_json() to elif request.is_json()

Expected Behavior:

Empty form submits should be allowed as they were. In the case of an empty form - None should be returned from the wrapper.

Environment:

- Python version: 3.8
- Flask-WTF version: 1.0.0
- Flask version: 2.1

**Comment by davidism** [comment]
Will make a 1.0.1 release soon.

**Comment by davidism** [comment]
Flask-WTF 1.0.1 is available: https://pypi.org/project/Flask-WTF/1.0.1/

**Comment by jwag956** [comment]
Thank you... thank you...
