### ISSUE TITLE
SupportAsync for validators

### ISSUE THREAD

**Issue by pythops** [wtforms/flask-wtf#522]
Hi,

It would be nice to able to able to support async for form validators.
```
async def validate_field_x(form, field_x):
     ....
     
class MyForm(FlaskForm):
    field_x = StringField("field X", validators=[validate_field_x])
````

Thanks

**Comment by davidism** [comment]
WTForms is a sync library. It is not possible to automatically run async functions like you're asking without introducing significant complexity and tradeoffs.

If you need to run an async function, you can use `asyncio.run()` from within a sync validator function. That will run async code, then return to the sync function and continue on.

**Comment by pythops** [comment]
Thanks for the answer.
Using `asyncio.run()` does not work actaully. I had to use https://github.com/erdewit/nest_asyncio to make it work
