### ISSUE TITLE
Flask g cache cause "The CSRF session token is missing" error

### ISSUE THREAD

**Issue by HelloYie** [wtforms/flask-wtf#534]
Logging in to one account with multiple browsers will cause CSRF token verification to fail because of the cache of flask "g"。

1. My backend code to generate csrf : 

```
sass_blueprint = Blueprint("sass", __name__, url_prefix="/api/cli")

@sass_blueprint.after_request
def after_request(response):
    csrf_token = generate_csrf()
    response.set_cookie("csrf_token", csrf_token)
    return response
```

3. The first browser I log into CSRF works fine
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/5723225/190882045-0efc0eb0-4a93-4e5a-8917-d855ae20728c.png">

4. I log into the same account with a second browser got  an error: "The CSRF session token is missing"
<img width="1254" alt="image" src="https://user-images.githubusercontent.com/5723225/190881998-70ab3fa1-c4cc-4985-91d2-7e1757a8332e.png">

5. I observed that flask g cache can cause this problem
<img width="779" alt="image" src="https://user-images.githubusercontent.com/5723225/190882119-2c928415-7147-4516-b6d9-f65d48c274ee.png">

6. My temporary solution

```
sass_blueprint = Blueprint("sass", __name__, url_prefix="/api/cli")

@sass_blueprint.before_request
def before_request():
    if 'csrf_token' in g:
        delattr(g, 'csrf_token')
```

**Comment by HelloYie** [comment]
I found that flask "g.xxx" is not reset after a request
<img width="987" alt="image" src="https://user-images.githubusercontent.com/5723225/190892278-4404545c-f684-4913-98ce-fed00feb0e6b.png">

test code:
```
sass_blueprint = Blueprint("sass", __name__, url_prefix="/api/cli")

@sass_blueprint.before_request
def before_request():
    try:
        print('xxxxxx in g:', 'xxxxxx' in g)

        if 'xxxxxx' not in g:
            print('set g xxxxxx......')
            setattr(g, 'xxxxxx', 'xxxxxx')
```

Then request the service several times，found that flask "g.xxx" is not reset after a request

Flask version:  2.0.1

**Comment by HelloYie** [comment]
I found that g is not destroyed after a request，so this caused the problem.
```
# test code
sass_blueprint = Blueprint("sass", __name__, url_prefix="/api/cli")

@sass_blueprint.before_request
def before_request():
    try:
        print('xxxxxx in g:', 'xxxxxx' in g)
        if 'xxxxxx' not in g:
            print('set g xxxxxx......')
            setattr(g, 'xxxxxx', 'xxxxxx')
```
![image](https://user-images.githubusercontent.com/5723225/190892668-5806ea99-4fcf-479d-a483-4aaef2afa8f9.png)
<img width="1197" alt="image" src="https://user-images.githubusercontent.com/5723225/190892558-29973183-3b75-4858-96e8-bdf840add1a1.png">
Flask: 2.0.1 
Link:  https://flask.palletsprojects.com/en/2.0.x/api/#flask.g

**Comment by davidism** [comment]
There is something else wrong with your code. `g` is not persisted across requests. Perhaps you're pushing an app context globally rather than letting Flask manage it per-request?

**Comment by HelloYie** [comment]
@davidism Thanks a lot ，I found that I use `app.app_context().push()` can cause this problem.
