### ISSUE TITLE
FR: Add Cloudflare Turnstile Captcha solution

### ISSUE THREAD

**Issue by fili** [wtforms/flask-wtf#535]
This is a feature request. 

See also: 
- https://blog.cloudflare.com/turnstile-private-captcha-alternative/
- https://developers.cloudflare.com/turnstile/get-started/migrating-from-recaptcha/

Pros:
- This particular Captcha service does not use cookies, and as such can be real alternative for Google's reCaptcha as a more privacy-friendly solution.

**Comment by davidism** [comment]
I don't plan to add more captch providers.
