### ISSUE TITLE
Autocomplete input suggestion field

### ISSUE THREAD

**Issue by xihajun** [wtforms/flask-wtf#551]
If it is possible to have a autocomplete input suggestion, I noticed that there is some implementation using javascript to enable it, but I wonder if that could be a field object of input?

[<img width="367" alt="image" src="https://user-images.githubusercontent.com/25631641/213230058-439a6387-bbb7-4844-93cd-8404027ee258.png">
](https://www.geeksforgeeks.org/autocomplete-input-suggestion-using-python-and-flask/)

**Comment by davidism** [comment]
This is outside the scope of this library. Pick a JavaScript library, such as [select2](https://select2.org/).
