### ISSUE TITLE
flask_wtf no longer compatible with flask 2.3.0

### ISSUE THREAD

**Issue by djundjila** [wtforms/flask-wtf#561]
Problem:

flask_wtf's `__init__` imports recaptcha, which in its `__init__` imports fields, which in turn imports widgets, where the line `from flask import Markup` raises an ImportError. According to the changelog in flask 2.3.0 this is only only deprecated, but apparently it is actually a breaking change

To reproduce it:

pip install flask 2.3.0 and do `flask_wtf.csrf import CSRFProtect

Expected behaviour that didn't happen:

Is should import CSRFProtect without rasing an ImportError.

Environment:

- Python version: 3.11
- Flask-WTF version: 1.1.1
- Flask version: 2.3.0

**Comment by davidism** [comment]
Flask 2.3.1 fixes the early removal, we'll still update Flask-WTF as well

**Comment by UniqASL** [comment]
Hi, it seems that I got an error linked with flask wtf recaptcha as well after updating from flask 2.2.3 to flask 2.3.2.:

> File "xxx/flask_wtf/recaptcha/widgets.py", line 6, in \<module\>
> JSONEncoder = json.JSONEncoder
> AttributeError: module 'flask.json' has no attribute 'JSONEncoder'

I downgraded back to flask 2.2.3 and it's working fine again.
