### ISSUE TITLE
changelog is missing entries for releases beyond version 1.0.1

### ISSUE THREAD

**Issue by gsmethells** [wtforms/flask-wtf#564]
The changelog stops at version 1.0.1 and the latest is version 1.1.1

View https://flask-wtf.readthedocs.io/en/1.0.x/changes/

The changelog should list and describe all available releases.

Environment:
N/A

**Comment by davidism** [comment]
https://flask-wtf.readthedocs.io/en/latest/changes/

**Comment by gsmethells** [comment]
@davidism the PyPI page https://pypi.org/project/Flask-WTF/ displays version 1.1.1 however the Links section on the PyPI page has 

Changes: https://flask-wtf.readthedocs.io/changes/

which goes to https://flask-wtf.readthedocs.io/en/1.0.x/changes/ 

hence this is not done yet. One cannot expect a user to manually change the URL bar contents to achieve the correct page.
