### ISSUE TITLE
debubpy + autoreload not working with FlaskForm

### ISSUE THREAD

**Issue by morindo** [wtforms/flask-wtf#600]
Greetings, I'm not sure if this issue is related to FlaskForm implementation but here's the problem.

I'm using VS Code + [debugpy ](https://github.com/microsoft/debugpy) extension to debug my Flask/Python code and I've also activated the autoReload feature to enable code reload. When I debug my Flask app there is no problem when I change code and refresh my page, it takes all the changes without the need to restart my app. But when I change a FlaskForm, the code is not autoReload and I get the following message in my VS Code (Python Debugger) Debug Console saying that debugpy was not able to reload the code due to a NoneType class.

VS Code Debug Console
```bash
code reload: Start reloading module: "app.routes.pages.strategies.forms" ... 
code reload: Type of: _unbound_fields (old: <class 'list'> != new: <class 'NoneType'>) changed... Skipping.
code reload: Type of: _wtforms_meta (old: <class 'type'> != new: <class 'NoneType'>) changed... Skipping.
code reload: reload finished without applying any change
```

forms.py
```python
from flask_wtf import FlaskForm
from wtforms import (
    StringField,
)
from wtforms.validators import DataRequired, Length


class StrategyForm(FlaskForm):
    name = StringField(
        "Name",
        validators=[DataRequired(), Length(min=3, max=40)],
        render_kw={"placeholder": "Strategy Name"},
    )
```

launch.json
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python Debugger: Flask",
            "type": "debugpy",
            "request": "launch",
            "module": "flask",
            "env": {
                "FLASK_APP": "app",
                "FLASK_DEBUG": "1",
                "FLASK_ENV": "development"
            },
            "autoReload": {
                "enable": true
            },
            "args": [
                "run",
                "--no-debugger",
                "--no-reload"
            ],
            "jinja": true,
            "justMyCode": true
        }
    ]
}
```
Do you think we can make to changes to the FlaskForm type to fix this?

I think that VS Code should be able to auto reload changes when a FlaskForm is modified and saved.

Environment:

- Python version: Python 3.12
- Flask-WTF version: 1.2.1
- Flask version: 3.0.3

Thank you very very much!

**Comment by davidism** [comment]
`autoReload` does not look like a feature you should be using, it seems to be trying to reload code in place, which is extremely unlikely to work with _any_ code, that isn't specific to Flask/WTForms. You'll need to report issues with that to that project.

**Comment by morindo** [comment]
> `autoReload` does not look like a feature you should be using, it seems to be trying to reload code in place, which is extremely unlikely to work with _any_ code, that isn't specific to Flask/WTForms. You'll need to report issues with that to that project.

Can you explain a little bit why autoReload does not look like a feature I should be using? I've been using autoReload for a year now without any problem. It's a HUGE time saver for development. Have you ever experienced debugpy + autoReload in Flask? It's a game changer! I would be willing to make you a private demo if you want.

Cheers,

**Comment by davidism** [comment]
I have no idea what it is. But patching live code is not something that we deal with. It's on the maintainers of that project to make it compatible.

**Comment by morindo** [comment]
I totally understand, I was not sure if it was a FlaskForm or debugpy issue. Here is the answer from debugpy. It's by design.

https://github.com/microsoft/debugpy/issues/1638#issuecomment-2251009065
